//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Invoice = new HashSet<Invoice>();
            this.Order = new HashSet<Order>();
        }

        public int Customer_Id { get; set; }
        [Required(ErrorMessage = "This Field Cannot Be Empty")]
        [DisplayName("Name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This Field Cannot Be Empty")]
        [DisplayName("Mobile No")]
        public Nullable<long> MobileNo { get; set; }
        [Required(ErrorMessage = "This Field Cannot Be Empty")]
        [DisplayName("Postal Code")]
        public Nullable<int> PostalCode { get; set; }
        [Required(ErrorMessage = "This Field Cannot Be Empty")]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
