//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using PagedList;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order = new HashSet<Order>();
            this.Seller = new HashSet<Seller>();
        }


        public int Id { get; set; }
        [Required(ErrorMessage = "This Field Cannot be Blank")]
        public string Name { get; set; }
        [Required(ErrorMessage = "This Field Cannot be Blank")]
        public Nullable<double> Price { get; set; }
        [Required(ErrorMessage = "This Field Cannot be Blank")]
        public string Description { get; set; }
        [DisplayName("Upload File")]
        public string Image { get; set; }


        public HttpPostedFileBase ImageFile { get; set; }
        [Required(ErrorMessage = "This Field Cannot be Blank")]
        public Nullable<int> Stock { get; set; }
        [Required(ErrorMessage = "This Field Cannot be Blank")]
        public string Category { get; set; }

        public string Display { get; set; }
        public Nullable<int> Category_Id { get; set; }

        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seller> Seller { get; set; }

        public static implicit operator PagedList<object>(Product v)
        {
            throw new NotImplementedException();
        }
    }
}
