//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCart1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seller
    {
        public int Seller_id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public Nullable<long> Mobile_No { get; set; }
        public Nullable<long> GSTIN { get; set; }
        public Nullable<long> Account_No { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Order_Id { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
